name: AAWP
version: '${version}'
main: io.turbo.random.aawp1.AAWP
api-version: '1.21'
description: A refactored version of AAWP (An Actual Warp Plugin)
author: TurboMaxe
load: STARTUP
permissions:
  AAWP.setwarp:
    description: "Allows players to use the setwarp command."
    default: op
  AAWP.warp:
    description: "Allows players to use the warp command."
    default: op
  AAWP.clearwarps:
    description: "Allows players to use the clearwarp command."
    default: op
  AAWP.aawp:
    description: "Fetches information about the plugin."
    default: op
   AAWP.version:
    description: "Allows players to see what version of AAWP is running."
    default: op
  AAWP.reloadconfig:
    description: "Reloads the config.yml."
    default: op
  AAWP.delwarp:
    description: "Deletes a specific warp."
    default: op
  AAWP.warps:
    description: "Returns a list of all warps."
    default: op
  AAWP.help:
    description: "Lists the commands."
    default: op

